language: Python
sudo: required

os:
  - linux

python:
  - "2.7"

virtualenv:
  - system_site_packages: true

before_install:
  - "sudo apt-get update"
  - "sudo apt-get -y install python-pygame"

install:
  - "python setup.py install"

script: "nose2 --plugin nose2.plugins.layers --log-capture -v"