language: Python
sudo: required

os:
  - linux

python:
  - "2.7"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get build-dep python-pygame"
  - "sudo apt-get install mercurial"
  - "hg clone https://bitbucket.org/pygame/pygame"
  - "cd pygame"
  - "python setup.py build"
  - "sudo python setup.py install"

install:
  - "python setup.py install"

script: "nose2 --plugin nose2.plugins.layers --log-capture -v"