language: Python
sudo: required

os:
  - linux
  - osx

python:
  - "2.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - "sudo apt-get install python-pygame"
  - "python setup.py install"

script: "nose2 --plugin nose2.plugins.layers --log-capture -v"