language: Python
sudo: required

os:
  - linux

python:
  - "2.7"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get build-dep python-pygame"
  - "sudo apt-get install python-pygame"

install:
  - "pip install pygame"
  - "python setup.py install"

script: "nose2 --plugin nose2.plugins.layers --log-capture -v"