language: Python
sudo: required

os:
  - linux

python:
  - "2.7"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get -y install mercurial python-dev libav-tools"
  - "sudo apt-get -y install libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev"
  - "sudo apt-get -y install libsdl1.2-dev  libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev"

install:
  - "pip install pygame"
  - "python setup.py install"

script: "nose2 --plugin nose2.plugins.layers --log-capture -v"